# Generated by Django 4.1.4 on 2023-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
